//ToDO LIST
//TABBAR
//BEST SELLER VC
// THIS FILE THAT CONTAINS THE COLECTION VIEW AND THE PICKER VIEW IS THE VIEW FILE .(BESTSELLER VIEW)
//1. CREATE COLLECTION VIEW(THIS IS A FILE BY ITSELF)
        // - SET LAYOUT
        // - SET BACKGROUND GOLOR
        // CONFORM TO DELEGATE AND DATASORCE SO WE DONT FORGET
        // REMEMBER TO SET THE CONSTRAINTS
    // - CREATE A CELL (THIS IS A FILE BY ITS SELF)
        // CREATE A IMAGE FOR BOOKCOVER
        // CREATE TEXT VIEW FOR BOOK DESCRIPTION
        // CREATE LABEL FOR AUTHOR NAME
// 2. CREATE PICKERvIEW TO DISPLAY CATEGORIES XDONE
//2A. NETWORK THINGS
// - WE TO MAKE A CALL TO GET CATEGORIES -> DISPLAY ON PICKER VIEW -> DOCUMENTS DIRECTORY (WE SAVE THIS SO WE DONT KEEP MAKING API CALLS )
// - WHEN WE CHOOSE A CATEGORY WE WANT TO GET THE BOOKS
        // WHEN WE GET BOOKS => WE NEED INFOMATION TO MAKE A MODEL, WE NEED TO DISPLAY THE INFORMATION ON THE COLLECTION VIEW
            // CREATE A SEGUE => FROM THE CELL TO THE DETAILLED VIEW

//
